services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: restaurante
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
